### ISSUE TITLE
Add drop cap styles

### ISSUE THREAD

**Issue by randseay** [TeamSkosh/fuselage#43]
This is what I used in the Skosh Site.

``` scss
.dropcap {
    span.initial-phrase {
        color: $brand-secondary;
        font-variant: small-caps;
    }

    &::first-letter {
        color: $brand-secondary;
        float: left;
        font-size: 324%;
        line-height: 0.95;
    }
}
```
