### ISSUE TITLE
Add a class to remove buttons' bottom margin

### ISSUE THREAD

**Issue by randseay** [TeamSkosh/fuselage#71]
The class should be called `inline` and targeted at the `button` class:

``` CSS
.button.inline {
    margin-bottom: 0;
}
```
